// <auto-generated />
using LottoLab.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LottoLab.Infra.Data.Migrations
{
    [DbContext(typeof(LotoChartsContext))]
    [Migration("20230302022500_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LottoLab.Domain.Data.Models.LotoFacil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Casa_1")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_10")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_11")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_12")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_13")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_14")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_15")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_2")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_3")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_4")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_5")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_6")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_7")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_8")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_9")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Concurso")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("LotoFacil", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
